### ISSUE TITLE
rosella on multiple samples

### ISSUE THREAD

**Issue by alienzj** [rhysnewell/rosella#10]
Hi, Newell, 
I like rosella, not only because I am a rust fan, but also because of the excellent performance of this tool.
In the documentation, you mentioned that rosella supports multi-sample binning, I know two cases:
1. co-assembly, and map multi samples to the co-assembly, then we got co-abundance, then binning;
2. combined single-assembly, and map multi samples to it, like vamb multisplit-binning mode.

Maybe you are one of the people who know the principle of binning best in the world, so I would like to ask you: suppose sample A is used to assemble metagenome A, then sample A, sample B, and sample C are compared to metagenome A, and then binning metagenome A, is this method advisable? 

Thanks~
Jie

**Comment by rhysnewell** [comment]
Hi Jie,

Thanks for your interest in Rosella! Rust is great, and you'll hopefully be able to get even better performance with the latest updates thanks to using some better FASTX sequence parsing libraries. 

So, just so I make sure I understand you are talking about mapping reads from samples to a metagenome even if those samples weren't used to create the assembly for metagenome A? This seems a little risky as I would think that the coverage profiles for samples B and C would be kind of inconsistent and you might just be adding noise to your analysis making it difficult for any binner to make sense of it.

On the other hand, if you were to somehow make sure that the samples you were using to compare were taxonomically very similar to sample A then maybe it would be okay? I would suggest using a tool like singleM to get OTU profiles, and then just make sure that sample A, B, and C are all fairly similar. I would not use sample B or C if they were completely distinct from sample A.

Cheers,
Rhys

**Comment by alienzj** [comment]
Hi, Newell,

Thank you for your explanation and suggestions.

I also think that comparing samples B and C back to genome A will cause interference.
VAMB's approach is to merge different assembly results together so that co-assembly can be avoided, but the corresponding calculation of co-abundance will be more expensive.
