### ISSUE TITLE
How will metabat based coverage depth and trimmed mean depth will affect binning result

### ISSUE THREAD

**Issue by jianshu93** [rhysnewell/rosella#14]
Dear rosella author,

I am wondering how different metric for coverage depth will affect the binning results because trimmed mean coverage depth will reduce the effect of conservative regions on calculating depth (e.g. 16S will be much high in depth comparing to other regions because a lot of reads from other genomes will be mapped)

Thanks,

Jianshu

**Comment by rhysnewell** [comment]
Hi Jianshu,

Different calculations for mean coverage and variance will undoubtedly change the results in some way. It's really difficult to say which method is the best way, but the metabat adjusted depth calculation and trimmed mean methods seem to be the most sensible and have provided reasonable results in the past. 

To be honest, it is not an area I have tested as much as I should have as I've been focused on different parts of the code and it seems like a rather tedious task to test. 

Cheers,
Rhys

**Comment by jianshu93** [comment]
I have done some testing on this using a real dataset. I am going to share the results with you and see how we could improve. I will share results with you via dropbox，can you please offer your email address？

thanks

Jianshu

**Comment by rhysnewell** [comment]
Sure thing, which versions of Rosella and flight did you use for these tests though?

Dropbox email: rhys.newell@hdr.qut.edu.au

Cheers,
Rhys
