### ISSUE TITLE
annembed for UMAP

### ISSUE THREAD

**Issue by jianshu93** [rhysnewell/rosella#23]
Dear Rosella team,

I noticed that you rely on the python UMAP for dimension reduction for binning, which relies on pydescant for nearest neighbor finding. However, HNSW is more efficient than pydescant for building small world graph/kgraph. I am wondering whether this could be useful, see here: https://github.com/jean-pierreBoth/annembed

Thanks,

Jianshu

**Comment by rhysnewell** [comment]
Hi Jianshu,

Thanks for pointing this out! Looks really cool, and is written in Rust which we love to see. We'll definitely keep an eye on this, but have no plans to port over right now. But it would be a nice consideration for future projects, for sure!

Cheers,
Rhys
