### ISSUE TITLE
package conflicts

### ISSUE THREAD

**Issue by janfelix** [rhysnewell/rosella#29]
Hi,

I have been trying to install rosella through conda. Conda is updated and I created a python 3.9 environment. However, I get package conflicts such as:

Package zlib conflicts for:
rosella -> zlib[version='>=1.2.11,<1.3.0a0']
python=3.9 -> zlib[version='>=1.2.11,<1.3.0a0|>=1.2.12,<1.3.0a0|>=1.2.13,<1.3.0a0']

...and many more. Sorry, maybe this is not a rosella issue, but maybe you have an idea what it could be. Edit: This also occurred in python 3.8

Thanks!

**Comment by rhysnewell** [comment]
Hello!

Thanks for checking out Rosella. This kind of seems like your conda channels might be out of order. Would you please be able to post the contents of your `~/.condarc` file? It should look something like this:

```
channels:
  - bioconda
  - conda-forge
  - defaults
```

**Comment by janfelix** [comment]
Hello, thanks for the fast reply. 

Yes, I really could have thought of that myself, conda-forge was missing. 

It worked now, thanks a lot!
