### ISSUE TITLE
Flight error.

### ISSUE THREAD

**Issue by Valentin-Bio** [rhysnewell/rosella#34]
Hello iI ran rosella over my paired end metagneomic sequencing data as the following:

rosella recover -r assembly/final.contigs.fa -1 *R1* -2 *R2* -o rosella_bins --threads 12 

On my output directory I have rosella_coverages.tsv  and rosella_kmer_table.tsv files

but looking to my log file, it seems that flight failed: 

> [2023-01-24T11:27:52Z INFO  rosella] rosella version 0.4.2
[2023-01-24T11:27:52Z INFO  rosella] Using min-covered-fraction 0%
[2023-01-24T11:27:52Z INFO  rosella] Using min-read-aligned-percent 0%
[2023-01-24T11:27:52Z INFO  coverm::mapping_index_maintenance] Generating MINIMAP2_SR index for assembly/final.contigs.fa ..
[2023-01-24T11:28:12Z INFO  coverm::mapping_index_maintenance] Finished generating MINIMAP2_SR index.
[2023-01-24T11:28:14Z INFO  rosella::estimation::contig] Processing short reads...
[2023-01-29T06:14:19Z ERROR bird_tool_utils::command] Error when running flight process. Exitstatus was : ExitStatus(unix_wait_status(256))
thread 'main' panicked at 'Failed to grab stderr from failed flight process', /home/conda/.cargo/registry/src/github.com-1ecc6299db9ec823/bird_tool_utils-0.3.0/src/command.rs:17:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

testing if flight was available I ran 

flight --help 

but I got another error message: 

> Traceback (most recent call last):
>   File "/home/toshiba/miniconda3/envs/rosella/bin/flight", line 5, in <module>
>     from flight.flight import main
>   File "/home/toshiba/miniconda3/envs/rosella/lib/python3.10/site-packages/flight/flight.py", line 22, in <module>
>     from Bio import SeqIO
>   File "/home/toshiba/.local/lib/python3.10/site-packages/Bio/SeqIO/__init__.py", line 374, in <module>
>     from Bio.Align import MultipleSeqAlignment
>   File "/home/toshiba/.local/lib/python3.10/site-packages/Bio/Align/__init__.py", line 35, in <module>
>     from Bio.Align import substitution_matrices
>   File "/home/toshiba/.local/lib/python3.10/site-packages/Bio/Align/substitution_matrices/__init__.py", line 15, in <module>
>     class Array(numpy.ndarray):
> AttributeError: module 'numpy' has no attribute 'ndarray'
>

**Comment by rhysnewell** [comment]
Interesting, looks like an error originating from the Biopython package using deprecated numpy features or maybe just a corrupted install. Have you tried:
```
pip uninstall Biopython
pip uninstall numpy
pip install Biopython
flight --help
```

**Comment by rhysnewell** [comment]
If this did not fix, then there may be a strange dependency issue with skbio so if you have any other errors pop up please post them here

**Comment by Valentin-Bio** [comment]
Hello, yes my server is down these days, I will give a try with your suggestions soon.

Thanks

**Comment by rhysnewell** [comment]
Hi @Valentin-Bio , Apologies for the delay I've been swamped but had some inspiration this weekend. `v0.5.0` should fix this issue if you create a new conda environment and install from the bioconda channel. If you still get an error from flight, please open a new issue and post the error log that gets produced. The flight error should be exposed to users now.
