### ISSUE TITLE
Rosella Installation dependent on Repository Cloning

### ISSUE THREAD

**Issue by ka-block** [rhysnewell/rosella#38]
We are currently using Rosella in our Snakemake workflow. However, we have tried to run Rosella with an installation via conda and ran into the reported “Flight Error” (#34 & #37). It only works when the entire Rosella repository is cloned into our workflow. This creates redundancy and makes providing the correct version to our workflow complicated. Additionally, we want to ensure proper credit without creating any misconceptions by cloning your work into our workflow.

It would be more convenient and efficient if Rosella could be installed without the need for cloning the entire repository. We kindly request you to have a look into this installation issue.

Feel free to reach out for more information.

Thank you for your time and help. We highly appreciate your work and hope to include Rosella into our workflow. 

Best regards,
Katharina

**Comment by rhysnewell** [comment]
Hi Katharina,

Thanks for reaching out. I'd love to get this fixed up, what would be the best solution for you? I've tried conda recipes in the past but the underlying python dependencies always seem to cause issues. Would a docker container be more suitable for your needs?

Cheers,
Rhys

**Comment by ka-block** [comment]
Hi Rhys,

Thank you for your quick reply. A docker container would be great. 

Many thanks in advance!

Best regards,
Katharina

**Comment by rhysnewell** [comment]
Hi @ka-block , Sorry this took so long but rather than creating a dockerfile I've created a new release with a lot of changes `v0.5.0`
It's dependency versions are locked pretty tight, and conda installation works from my testing
