### ISSUE TITLE
failed flight process

### ISSUE THREAD

**Issue by TJrogers86** [rhysnewell/rosella#40]
I've tried everything I know to do but I still get the following error:

<img width="1287" alt="image" src="https://github.com/rhysnewell/rosella/assets/48442658/4d7fc21a-d71d-4b4f-930a-147646a77766">

Here is my code:
<img width="1208" alt="image" src="https://github.com/rhysnewell/rosella/assets/48442658/6bf66e79-47d4-42c5-9475-b8adfe3ddbfb">

**Comment by rhysnewell** [comment]
Hello,

Would it be possible to get some assembly quality statistics for the fasta files you are trying to bin? Use `stats.sh` from `bbmap`, and show me what the contig size distribution looks like

Cheers,
Rhys

**Comment by TJrogers86** [comment]
<img width="1101" alt="image" src="https://github.com/rhysnewell/rosella/assets/48442658/790528d3-a836-41db-93ae-eebc3f67a14a">
If this isnt the right info you need, let me know and I will run the stats.sh

**Comment by Valentin-Bio** [comment]
Hello! I'm getting the same problem running on a Ubuntu machine. I attach here the result of the stats.sh program.
[assembly_stats.txt](https://github.com/rhysnewell/rosella/files/13064404/assembly_stats.txt)

**Comment by Valentin-Bio** [comment]
Does this error comes from flight bin command isn't it ?. If so can it be that the program is not reading properly the coverage file ?. The coverage file that I provide is the output of metabat2 `jgi_summarize_bam_contig_depths` algorithm. Taking a look into it , it has 2 columns per each sample but one of the pair having a '_var' suffix which I think is the adjusted coverage value. Does flight takes the adjusted coverage column of the respective sample ?

**Comment by rhysnewell** [comment]
Could you try letting rosella generate the coverage results by providing the reads directly to the program? the '_var' columns represent the variance of coverage along a contig, the coverage files should look pretty similar between metabat2 and rosella but there might be something happening with the column headers

**Comment by rhysnewell** [comment]
Hey @TJrogers86 and @Valentin-Bio, Apologies for the delay on this but I'm hoping that this is fixedin `v0.5.0`. If not then then flight error should be exposed so we can properly debug it

**Comment by rhysnewell** [comment]
If you do get time to re-run this and it still fails, please open up a new issue with the actual error being produced from flight and we can go from there but I'll close this now as flight errors are exposed now
