### ISSUE TITLE
rosella.yml specifies numpy <=1.21 but numba requires numpy >= 1.22

### ISSUE THREAD

**Issue by jvollme** [rhysnewell/rosella#42]
Hi, I keep getting errors at the flight step in my existing rosella installations ( I already tried reinstalling in a new environment, but get [a different error](#41 ) there). 
Teh error includes the message : ```File \"/home/ww5070/.conda/envs/rosella/lib/python3.10/site-packages/numba/__init__.py\", line 40, in _ensure_critical_deps\n    raise ImportError(msg)\nImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.\n"```

No idea why rosella used to work in the past but does not anymore now, but checking the __init__.py of numba and the specifications in rosella.yml confirms that numba specifically checks for numpy >= 1.22 but that numpy <=1.21 is actually specified in [rosella.yml](https://github.com/rhysnewell/rosella/blob/main/rosella.yml).

So probably either the required numpy version in rosella.yml or the numba requirement need to be corrected?

**Comment by jvollme** [comment]
Update: Turns out I just had to update numpy to numpy=1.23.2 with ```conda install -n rosella numpy=1.23.2``` (and had actually done so in other pre-existing rosella environments that i had forgotten about...) for flight (and consequently rosella) to work

So the numpy requirement definitively should be updated in rosella.yml...

**Comment by rhysnewell** [comment]
Should be fixed in `v0.5.0`
